import { FileText, Clock, Sparkles, ChevronDown, ChevronUp, Plus, MoreVertical, Edit, Trash2 } from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { motion, AnimatePresence } from 'motion/react';
import { useState } from 'react';
import { AddContentDialog } from './AddContentDialog';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from './ui/dropdown-menu';

interface SummaryProps {
  onSelectSummary?: (summaryId: string) => void;
}

interface Summary {
  id: string;
  documentTitle: string;
  dateCreated: string;
  keyPoints: string[];
  fullSummary: string;
}

const mockSummaries: Summary[] = [
  {
    id: '1',
    documentTitle: 'Biology 101 Notes',
    dateCreated: 'Jan 8, 2026',
    keyPoints: [
      'Cell structure and function',
      'Mitochondria as the powerhouse of the cell',
      'DNA replication process',
      'Protein synthesis overview',
    ],
    fullSummary: 'This comprehensive biology chapter covers the fundamental aspects of cell biology, including detailed explanations of cell structure, organelles, and their functions. Special emphasis is placed on the role of mitochondria in cellular respiration and energy production.',
  },
  {
    id: '2',
    documentTitle: 'World History Chapter 5',
    dateCreated: 'Jan 7, 2026',
    keyPoints: [
      'Rise of ancient civilizations',
      'Egyptian pyramids and culture',
      'Mesopotamian writing systems',
      'Trade routes and economic development',
    ],
    fullSummary: 'This chapter explores the development of early civilizations in the ancient world, focusing on Egypt and Mesopotamia. It discusses architectural achievements, writing systems, and the role of trade in cultural exchange.',
  },
  {
    id: '3',
    documentTitle: 'Physics Lecture Slides',
    dateCreated: 'Jan 5, 2026',
    keyPoints: [
      "Newton's laws of motion",
      'Force, mass, and acceleration',
      'Friction and air resistance',
      'Applications in real-world scenarios',
    ],
    fullSummary: "An in-depth look at Newton's three laws of motion and their applications. The lecture covers fundamental concepts of force, mass, and acceleration, with practical examples demonstrating these principles in everyday life.",
  },
  {
    id: '4',
    documentTitle: 'Chemistry Lab Report',
    dateCreated: 'Jan 3, 2026',
    keyPoints: [
      'Chemical reactions and equations',
      'Balancing chemical equations',
      'Types of reactions: synthesis, decomposition',
      'Lab safety procedures',
    ],
    fullSummary: 'This lab report details various types of chemical reactions observed in laboratory settings. It includes step-by-step procedures, observations, and conclusions about synthesis and decomposition reactions.',
  },
];

export function Summary({ onSelectSummary }: SummaryProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [isAddDialogOpen, setAddDialogOpen] = useState(false);

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <div className="flex-1 overflow-auto">
      <div className="max-w-5xl mx-auto p-4 lg:p-8 pb-20 lg:pb-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="w-6 h-6 text-primary" />
              <h1>AI Summaries</h1>
            </div>
            <p className="text-muted-foreground">
              All your document summaries generated by AI
            </p>
          </div>
          <Button onClick={() => setAddDialogOpen(true)}>
            <Plus className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">Generate Summary</span>
            <span className="sm:hidden">New</span>
          </Button>
        </div>

        {/* Summaries List */}
        <div className="space-y-4">
          {mockSummaries.map((summary, index) => (
            <motion.div
              key={summary.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: index * 0.05 }}
            >
              <Card className="overflow-hidden">
                <div className="p-6">
                  {/* Header */}
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <FileText className="w-4 h-4 text-primary" />
                        <h3>{summary.documentTitle}</h3>
                      </div>
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Clock className="w-3 h-3" />
                        <span>{summary.dateCreated}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge className="bg-primary/10 text-primary border-primary/20">
                        AI Generated
                      </Badge>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon">
                            <MoreVertical className="w-4 h-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent className="w-56">
                          <DropdownMenuItem>
                            <Edit className="w-4 h-4 mr-2" />
                            Edit
                          </DropdownMenuItem>
                          <DropdownMenuItem variant="destructive">
                            <Trash2 className="w-4 h-4 mr-2" />
                            Delete
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </div>
                  </div>

                  {/* Key Points */}
                  <div className="mb-4">
                    <h4 className="text-sm font-medium mb-3">Key Points</h4>
                    <ul className="space-y-2">
                      {summary.keyPoints.map((point, idx) => (
                        <li key={idx} className="flex items-start gap-2 text-sm">
                          <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 flex-shrink-0" />
                          <span className="text-muted-foreground">{point}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Full Summary (Collapsible) */}
                  <AnimatePresence>
                    {expandedId === summary.id && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden"
                      >
                        <div className="pt-4 border-t border-border">
                          <h4 className="text-sm font-medium mb-3">Full Summary</h4>
                          <p className="text-sm text-muted-foreground leading-relaxed">
                            {summary.fullSummary}
                          </p>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>

                  {/* Toggle Button */}
                  <Button
                    variant="ghost"
                    className="w-full mt-4"
                    onClick={() => toggleExpand(summary.id)}
                  >
                    {expandedId === summary.id ? (
                      <>
                        <ChevronUp className="w-4 h-4 mr-2" />
                        Show Less
                      </>
                    ) : (
                      <>
                        <ChevronDown className="w-4 h-4 mr-2" />
                        Show Full Summary
                      </>
                    )}
                  </Button>
                </div>
              </Card>
            </motion.div>
          ))}
        </div>

        {/* Empty State */}
        {mockSummaries.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20">
            <Sparkles className="w-20 h-20 text-muted-foreground/50 mb-4" />
            <h3 className="mb-2">No summaries yet</h3>
            <p className="text-muted-foreground mb-6 text-center max-w-md">
              Upload a document and generate a summary to see it here
            </p>
          </div>
        )}
      </div>

      <AddContentDialog 
        open={isAddDialogOpen} 
        onClose={() => setAddDialogOpen(false)} 
        mode="summary" 
      />
    </div>
  );
}